aws_region               = "us-west-1"
friendly_name_prefix     = "tfe"
tfe_hostname             = "bhacmecorp.com"
tfe_license_file_path    = "./terraform-chip.rli"
route53_hosted_zone_name = "bhacmecorp.com"
tls_certificate_arn      = "arn:aws:acm:us-west-1:072246857943:certificate/62ca21cd-165c-4d23-bc5c-3474bb7ea8a5"
instance_size            = "t2.small"
rds_instance_size        = "db.t3.medium"
